# Generated by Django 5.2.8 on 2025-12-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoMoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concessionnaire',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='concessionnaire',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='updated_at',
        ),
    ]
